# example

#### [1] Cut the Rope
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

In [ ]:
import numpy as np
a = np.linspace(0,5,10)

for ele in a[1:10]:
    print(f"{ele:.2f}")

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.00


#### [2] Non-Zero elements

#### Find indices of non-zero elements from the array [1,2,0,0,4,0] ? Print the index of non-zero elements.

In [ ]:
import numpy as np
# a = [1,2,0,0,4,0] 

# for i in range(len(a)):
#     if a[i] != 0:
#         print(i, end=' ')

a = np.array([1,2,0,0,4,0])
index = np.where(a != 0)
for i in index[0]:
    print(i, end=' ') # => 0 1 4 

0 1 4 

In [ ]:
print(index)
# for i in index:
#     print(i, end=' ')  => [0 1 4] 

(array([0, 1, 4]),)


In [ ]:
index[0]

array([0, 1, 4])

In [ ]:
print(*index)

[0 1 4]


In [ ]:
print(np.where(a != 0))

(array([0, 1, 4]),)


In [ ]:
print(np.where(a != 0)[0])
for indx in np.where(a != 0)[0]:
    print(indx)

[0 1 4]
0
1
4


In [ ]:
a = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
index = np.where(a%3 == 0)

for i in index[0]:
    print(i, end=' ')

1 4 7 

In [ ]:
for i in np.where(a%3 == 0)[0]:
    print(i, end=' ')

1 4 7 

##### Given an integer array of size 10. Replace the odd number in numpy array with -1 ?

In [ ]:
import numpy as np
a = np.arange(1,11,1)
a[ a%2 != 0] = -1
for ele in a:
    print(ele, end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [ ]:
a = np.arange(1,11,1)
print(a)
print(np.where(a%2 != 0, -1, a))

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


###Given an integer array of size 9 and replace the first occurrence of maximum value by 0?

In [ ]:
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a [ a.argmax()] = 0
for ele in a:
    print(ele, end=' ')

11 2 13 4 15 6 0 8 19 

#### Negate Elements

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

In [ ]:
a = np.arange(1, 11)

index = np.where((a>=3) & (a<=8))
a[index] *= -1
for ele in a:
    print(ele, end=' ')

1 2 -3 -4 -5 -6 -7 -8 9 10 

In [ ]:
a = np.arange(1, 11)
index = np.where((a>=3) & (a<=8))
a = a[index]
a = np.negative(a)
print(a)

[-3 -4 -5 -6 -7 -8]


In [ ]:
np.where((a>=3) & (a<=8), -1*a, a)

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### Print the age of those students whose height is above 155 cm.

In [ ]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

index = np.where(height>155)
b = age[index]
c = height[index]

for i in range(len(b)) :
    print(b[i],c[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


#### [3] Sort by column(argsort() function)
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.

In [ ]:
import numpy as np
a = np.arange(21,1,-1)
a = a.reshape(4,5)
#sorted_arr = a[np.argsort(a[:,1])]    
sorted_arr = a[a[:,1].argsort()]    
print(sorted_arr)
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


#### [4] Killed in USA
Find value of killed column only where country == ‘United States’? Print 0 in place of missing values. Print count of Killed as integer value. Killed1 Killed2 Killed3. . .

In [ ]:
import csv
with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace= True)
    killed = []
    for row in file_data:
        if row['Country'] == 'United States':
            killed.append(row['Killed'])

import numpy as np
killed_np = np.array(killed)
killed_np[killed_np==''] = '0.0'
killed_np = np.array(killed_np, dtype=float)
# for kill in killed_np:
#     print(int(kill))
tatal_killed = int(np.sum(killed_np))
print(tatal_killed)

3771


In [ ]:
import numpy as np
import csv

with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv') as obj:
    data = csv.DictReader(obj, skipinitialspace=True)
    
    country = []
    killed = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])
        
np_killed = np.array(killed)
np_killed[np_killed == ''] = '0.0'
np_killed = np.array(np_killed, dtype=float)

np_country = np.array(country)
bool_usa = np_country == 'United States'
usa_killed = np_killed[bool_usa]

#total_killed_in_us = np.sum(usa_killed)   
#total_killed_in_us = sum(usa_killed) 
#total_killed_in_us = usa_killed.sum() 

# for kill in usa_killed:
#     print(int(kill))
print(usa_killed.sum())

3771.0


In [ ]:
import numpy as np
import csv

with open('/content/drive/MyDrive/Colab Notebooks/10year2017.csv') as file_obj:
    file_dict = csv.DictReader(file_obj, skipinitialspace = True)
    killed = []
    wounded = []
    country = []
    for row in file_dict:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])

#np_killed = np.array(killed, dtype = int) error bcz str can't directly converted into int
#np_killed = np.array(killed, dtype = float) error bcz of missing value
np_killed = np.array(killed)
print(np_killed=='')
#print(np_killed[np_killed=='']) #will return all missing value array
np_killed[np_killed==''] = '0.0'
print(np_killed[np_killed=='']) #returning empty array as there is no missing value now
np_killed = np.array(np_killed, dtype=float)

np_wounded = np.array(wounded)
np_wounded[np_wounded == ''] = '0.0' #bcz if we remove it then size will may differ from other matrix
np_wounded = np.array(np_wounded, dtype=float)

killed_wounded = np_killed + np_wounded

#now i want to know only india's data
np_country = np.array(country)
#np_country[np_country == 'India']
bool_country = np_country == 'India'
ans = killed_wounded[bool_country]
#print(ans)
print(sum(ans)) #india's killed and wounded people
print(sum(killed_wounded)) #total

[False False False ... False False False]
[]
1167.0
51372.0


#### [5] Terrorism Day
Find the number of attack held between day 10 and day 20 ignoring the year and month(including both day) Print count of NumberOFAttack as integer value.

In [ ]:
import csv
import numpy as np

file_obj = open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv')
data = csv.DictReader(file_obj, skipinitialspace=True)
#file_obj.close()
day_wise_attack = []
for row in data:
    day_wise_attack.append(row['Day'])
file_obj.close()  

npDay = np.array(day_wise_attack, dtype=float)
npDay = npDay[(npDay>=10) & (npDay<=20)]
print(npDay.shape[0])
#print(len(npDay))

66330


#### [6] Terrorism Date
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date). Note Ignore the case where day is 0 Print count of NumberOFAttack as integer value.

In [ ]:
import numpy as np
import csv

path = '/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv'
date = []
with open(path, 'r', encoding = 'ISO-8859-1') as data:
    reader = csv.DictReader(data, skipinitialspace=True)
    for row in reader:
        date.append([row['Day'], row['Month'], row['Year']])

npDate = np.array(date, dtype=int)
npDate = npDate[npDate[:, 2] == 2010]
npDate = npDate[npDate[:, 1] == 1]
npDate = npDate[npDate[:, 0] >= 1]
print(npDate.shape[0])

271


In [ ]:
#using boolean array
import csv
import numpy as np
data_1 = open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv' )
data = csv.DictReader(data_1,  skipinitialspace = 'True')

year = []
month = []
day = []

for row in data:
    if(row['Day']!='0'): #0 excluded
        year.append(row['Year'])
        month.append(row['Month'])   

np_year = np.array(year , dtype = float)
np_month = np.array(month , dtype = float)

year2010 = np_year == 2010 #boolean
month = np_month == 1 #boolean
arr = year2010[month] #boolean False False = False, F T = T
print(arr)
print(arr.shape[0])
print(np.sum(arr)) #  T=1 F=0

np_month = np_month[year2010]
np_month = np_month[np_month == 1] 
print(np_month.shape[0])

[False False False ... False False False]
14842
271
271


In [ ]:
#using where
import numpy as np
import csv

with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv') as obj :
    data = csv.DictReader(obj, skipinitialspace=True)
    
    day = []
    month = []
    year = []
    for row in data:
        day.append(row['Day'])
        month.append(row['Month'])
        year.append(row['Year'])
        
npYear = np.array(year, dtype=float)
index_2010 = np.where(npYear==2010)

np_month = np.array(month, dtype=float)
np_monthsOf2010 = np_month[index_2010]
index_jan2010 = np.where(np_monthsOf2010 == 1)

np_day = np.array(day, dtype=float)
np_allDays_jan2010 = np_day[index_jan2010]
#index = np.where( &)

np_excluding_Zero = np_allDays_jan2010[(np_allDays_jan2010>=1) & (np_allDays_jan2010<=31)]

ans = np_excluding_Zero.shape[0]
print(int(ans))

270


#### [7] Terror Casualty Attack
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.

In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.

So find out the attack in this period in which maximum casualties happened. Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.

Output Format : Casualty(int) City TerroristGroup

In [ ]:
import csv
import numpy as np
casualty=[]
city=[]
## Here we filter out the data
with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv', 'r', encoding = 'ISO-8859-1') as data:
    reader = csv.DictReader(data, skipinitialspace = True)
    for row in reader:
        if row['State']=='Jammu and Kashmir' and row['Year']=='1999':
            if row['Month']=='5' or row['Month']=='6' or row['Month']==7:
                city.append([row['City'],row['Group']])
                casualty.append([row['Killed'],row['Wounded']])
npcasualty=np.array(casualty)
npcity=np.array(city)
## Coverting the empty values present in Killed and wounded feature to Zero 
npcasualty[npcasualty=='']=0
## Converting the string value to float 
npcasualty=np.array(npcasualty,dtype=float)
## Now Summing up the Killed and wounded feature to find out the casualty 
npcasualty=np.sum(npcasualty,axis=1) 
index=np.argmax(npcasualty)
print(int(npcasualty[index]),npcity[index][0],npcity[index][1]) 

22 Kargil District Separatists


#### [8] Terror Casualty Red
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
Note: Casualty=Killed +Wounded
Print count of Casualty as integer value.

In [ ]:
import numpy as np
import csv
path = '/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv'
casuality = []
with open(path) as file_data:
    file_data = csv.DictReader(file_data, skipinitialspace=True)
    for row in file_data:
        if(row['State']=='Jharkhand' or row['State']=='Odisha' or row['State']=='Andhra Pradesh' or row['State']=='Chhattisgarh'):
            casuality.append([row['Killed'], row['Wounded']])
            
np_casuality = np.array(casuality)
np_casuality[np_casuality == ''] = 0
np_casuality = np.array(np_casuality, dtype=float)
np_casulaity_1D = np.sum(np_casuality, axis=1)
print(int(np.sum(np_casuality)))

5628


#### [9] Terror City Casualty
Find top 5 Indian Cities which has most number of casualties ?

Print count of Casualty as 
Note: Ignoring the City which is Unknown.
Output Format :

city_1 casualty_1(integer value) ...

city_5 casualty_5

In [ ]:
import numpy as np
import csv
casuality = []
city = []
with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv','r',encoding='ISO-8859-1') as file_obj:
    file_dict = csv.DictReader(file_obj, skipinitialspace = True)
    for row in file_dict:
        if (row['Country']=='India') and (row["City"]!='Unknown'):
            casuality.append([row['Killed'],row['Wounded']])
            city.append(row['City'])

np_casuality = np.array(casuality)
np_casuality[np_casuality == ''] = 0
np_casuality = np.array(np_casuality, dtype=float)
np_casulaity_1D = np.sum(np_casuality, axis=1)
npcity=np.array(city)

def cityWiseCasuality(city_arr, casu):
    ansArr = []
    city_list = np.unique(city_arr)
    for city in city_list:
        #finding all indx of particular city
        indx, = np.where(city_arr == city)
        sum = np.sum(casu[indx])
        ansArr.append([sum, city])
    ansArr.sort(reverse=True)
    return ansArr

city_casu = cityWiseCasuality(npcity, np_casulaity_1D)
for i in range(5):
    print(city_casu[i][1], city_casu[i][0])

Srinagar 3134.0
New Delhi 2095.0
Mumbai 2016.0
Jammu 1119.0
Guwahati 822.0


#### [10] Terrorism FrequentDay
Find the most frequent day of attack in a terrorismDataset ? Print count of frequent day and number of attack as Integer value.

In [ ]:
import numpy as np
import csv
day = []
with open('/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv','r',encoding='ISO-8859-1') as file_obj:
    file_dict = csv.DictReader(file_obj, skipinitialspace = True)
    for row in file_dict:
        day.append(row['Day'])

npDay = np.array(day)
uniqueDay, counts = np.unique(npDay, return_counts=True)
indx = counts.argmax()
print(uniqueDay[indx], counts[indx])

15 6500


In [ ]:
np.unique(npDay, return_counts=True)

(array(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18',
        '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28',
        '29', '3', '30', '31', '4', '5', '6', '7', '8', '9'], dtype='<U2'),
 array([ 891, 6344, 6064, 5936, 6012, 6043, 6028, 6500, 6112, 5852, 5880,
        5973, 5954, 5930, 5827, 5799, 5782, 5752, 5875, 5823, 5937, 6027,
        5507, 6011, 5046, 3095, 6153, 5844, 5781, 5997, 5859, 6057]))

In [ ]:
np.unique(npDay) #by default return_counts=False

array(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28',
       '29', '3', '30', '31', '4', '5', '6', '7', '8', '9'], dtype='<U2')

In [ ]:
#without numpy
import csv
with open("/content/drive/MyDrive/Colab Notebooks/10terrorismData.csv",encoding='ISO-8859-1') as file_obj:
    file_data=csv.DictReader(file_obj)
    
    dict={}
    for row in file_data:
        day=row["Day"]
        dict[day]=dict.get(day,0)+1  # dic contains the maximum pairs 
        
    max_key = max(dict, key=dict.get) # max key
    max_value = max(dict.values()) #max value
    print(max_key,max_value)

15 6500


In [ ]:
dict.values()

dict_values([5954, 891, 6344, 6011, 5781, 5859, 6057, 6064, 5936, 6012, 6043, 6028, 6500, 5973, 5930, 5827, 5799, 5875, 5823, 5937, 6027, 5046, 3095, 6153, 5997, 6112, 5852, 5880, 5782, 5752, 5844, 5507])

In [ ]:
dict.get

<function dict.get>

In [ ]:
max(dict, key=dict.get)

'15'

In [ ]:
dict

{'0': 891,
 '1': 6344,
 '10': 6064,
 '11': 5936,
 '12': 6012,
 '13': 6043,
 '14': 6028,
 '15': 6500,
 '16': 6112,
 '17': 5852,
 '18': 5880,
 '19': 5973,
 '2': 5954,
 '20': 5930,
 '21': 5827,
 '22': 5799,
 '23': 5782,
 '24': 5752,
 '25': 5875,
 '26': 5823,
 '27': 5937,
 '28': 6027,
 '29': 5507,
 '3': 6011,
 '30': 5046,
 '31': 3095,
 '4': 6153,
 '5': 5844,
 '6': 5781,
 '7': 5997,
 '8': 5859,
 '9': 6057}